# Задание 2.

**NB. Все упражнения ниже нужно делать без использования циклов Python в явном (`while`, `for`) и неявном виде (list comprehension, `map`, `reduce` и пр)**

Задания по манипуляциям с массивами чаще всего решаются в одно/два выражения. 

In [1]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme()

A = np.random.randint(0, 100, size=(200, 50))
A

array([[67,  3, 68, ..., 71, 19, 34],
       [30, 96, 20, ...,  4, 96, 28],
       [14, 81, 38, ..., 82, 44, 85],
       ...,
       [87, 15, 20, ..., 85, 42, 73],
       [55, 21, 20, ..., 67, 40, 13],
       [ 5, 14, 74, ..., 51, 97, 42]])

# Задание 2.1 (2 балла)

Сгенерируйте новый массив, в котором столбцы массива `A` переставлены в случайном порядке

In [3]:
import numpy as np

A = np.random.randint(0, 100, size=(200, 50))
A_shuffled = A[:, np.random.permutation(A.shape[1])]
print(A_shuffled)



[[ 8 79 24 ... 88 36  9]
 [67 20  5 ...  9 62  7]
 [31 63 25 ... 94 62 90]
 ...
 [26  3 44 ... 11  2 10]
 [53 83 93 ... 14  3 81]
 [83 58 18 ... 21 93 62]]


# Задание 2.2 (4 балла)

Сгенерируйте новый массив, который содержит только те строки массива `A`, в которых: 
- сумма элементов по четным столбцам (индексы $0, 2, \ldots$) больше среднего значения (по всему массиву) суммы элементов по нечетным столбцам (индексы $1, 3, \ldots$) 

In [4]:
import numpy as np
A = np.random.randint(0, 100, size=(200, 50))
even_columns_sum = A[:, ::2].sum(axis=1)
odd_columns_sum = A[:, 1::2].sum(axis=1)
odd_columns_avg_sum = odd_columns_sum.mean()
filtered_rows = A[even_columns_sum > odd_columns_avg_sum]
# Печать результата
print(filtered_rows)


[[53 95 41 ... 65 66 20]
 [ 1 34 72 ... 43 35 18]
 [94 10 61 ... 95 87 87]
 ...
 [69 56 17 ... 96 31 98]
 [ 0 30 95 ... 24 90 18]
 [56 91 20 ... 60 93 79]]


# Задача 2.3 (3 балла)

Найдите индекс строки массива `A`, в которой разница между максимальным и минимальным элементом максимальна

In [6]:
import numpy as np

# Генерация случайного массива A
A = np.random.randint(0, 100, size=(200, 50))
row_differences = A.max(axis=1) - A.min(axis=1)
max_difference_row_index = np.argmax(row_differences)

print(f"Индекс строки с максимальной разницей: {max_difference_row_index}")


Индекс строки с максимальной разницей: 0


# Задание 2.4 (5 баллов)

Сгенерируйте массив той же размерности, что и `A`, но в котором каждый элемент заменен на его порядковый номер (начиная с 1) в отсортированном по возрастанию массиве из элементов `A`

Если `A` выглядит так:
$$
\begin{pmatrix}
12 & 14\\
1 & 2
\end{pmatrix}
$$
то результат должен быть
$$
\begin{pmatrix}
3 & 4\\
1 & 2
\end{pmatrix}
$$

*Tip: рассмотрите возможность неоднократного применения [argsort()](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.argsort.html)*

In [7]:
import numpy as np

A = np.random.randint(0, 100, size=(200, 50))

sorted_A = np.sort(A, axis=None)

sorted_indices = np.argsort(A, axis=None)

ranked_A = np.argsort(np.argsort(A, axis=None).reshape(A.shape), axis=None) + 1

# Печать нового массива
print(ranked_A)


[2173 3496 3503 ... 2885 4618 3864]


# Задание 2.5 (2 балла)

Примените $\min-\max$ - нормализацию к строкам массива `A`. То есть нужно получить новый массивы, в каждой строке которого максимальный элементы равен $1$, минимальный - $0$. 

In [11]:
import numpy as np

A = np.random.randint(0, 100, size=(200, 50))
A_normalized = (A - A.min(axis=1, keepdims=True)) / (A.max(axis=1, keepdims=True) - A.min(axis=1, keepdims=True))

# Проверка результата
print(A_normalized)


[[0.02020202 0.53535354 0.62626263 ... 0.97979798 0.44444444 0.01010101]
 [0.34693878 0.59183673 0.43877551 ... 0.15306122 0.51020408 0.58163265]
 [0.66666667 0.57291667 0.32291667 ... 0.30208333 0.77083333 0.45833333]
 ...
 [0.76041667 0.57291667 0.19791667 ... 0.125      0.89583333 0.        ]
 [0.09278351 0.6185567  0.58762887 ... 0.8556701  0.06185567 0.07216495]
 [0.04123711 0.86597938 0.20618557 ... 0.02061856 0.13402062 0.35051546]]


# Задание 2.6 (2 балла)

Сгенерируйте новый трехмерный массив, размерности $10 \times 200 \times 50$. Подмассивы по нулевой оси должны состоять из элементов `A`, умноженных на $1 - 10$ соответственно

In [9]:
import numpy as np

# Генерация массива A размерности 200x50
A = np.random.randint(0, 100, size=(200, 50))

# Создание трехмерного массива размерности 100x200x50
# Подмассивы по нулевой оси должны быть умножены на числа от 1 до 10
A_3d = np.array([A * ((i % 10) + 1) for i in range(100)])

# Проверка результата
print(A_3d.shape)


(100, 200, 50)


# Задание 2.7 (2 балла)

Создайте новый массив, такой же размерности, как и `A`, в котором сначала сгруппированы четные столбцы `A`, потом  нечетные. Используйте [np.concat()](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html) 

In [13]:
import numpy as np

# Генерация массива A размерности 200x50
A = np.random.randint(0, 100, size=(200, 50))

even_columns = A[:, ::2]  # Четные столбцы (индексы 0, 2, 4, ...)
odd_columns = A[:, 1::2]  # Нечетные столбцы (индексы 1, 3, 5, ...)

A_grouped = np.concatenate((even_columns, odd_columns), axis=1)
print(A_grouped)


[[48  7 67 ...  4  4 40]
 [29  7 97 ... 61 69 48]
 [68  7 53 ... 59 51 65]
 ...
 [34 92 46 ... 92 68 48]
 [74 83  5 ... 37 35 57]
 [ 6 41 50 ... 75 95 15]]


# Задание 2.8 (2 балла)

Посчитайте количество строк массива `A`, в который все элементы больше 5. Используйте [np.all()](https://numpy.org/doc/stable/reference/generated/numpy.all.html) 

In [14]:
import numpy as np

A = np.random.randint(0, 100, size=(200, 50))

rows_all_greater_than_5 = np.all(A > 5, axis=1)

count_rows = np.sum(rows_all_greater_than_5)

print(f'Количество строк, в которых все элементы больше 5: {count_rows}')


Количество строк, в которых все элементы больше 5: 9


# Задание 2.9 (2 балла)

Поделите массив `A` горизонтально на 10 частей и создайте новый массив размерности $20 \times 50$, который является средним этих частей. Используйте [np.split()](https://numpy.org/doc/stable/reference/generated/numpy.split.html)

In [15]:
import numpy as np

# Генерация массива A размерности 200x50
A = np.random.randint(0, 100, size=(200, 50))
A_split = np.split(A, 10, axis=0)
A_avg = np.mean(A_split, axis=0)

# Печать результата
print(A_avg)
print(A_avg.shape)


[[47.9 46.7 55.6 45.9 35.7 60.1 61.  42.5 40.4 58.1 54.8 45.2 49.9 50.3
  55.7 44.  41.1 50.7 59.2 48.3 30.2 49.8 32.4 41.5 53.8 52.  69.5 55.9
  50.5 57.9 31.5 53.  53.1 61.6 41.7 46.2 45.5 49.4 58.5 40.1 30.7 54.3
  66.2 40.9 46.8 36.9 39.3 41.9 49.8 55.4]
 [76.6 42.1 48.3 70.6 37.8 34.4 51.6 46.5 61.1 56.2 35.8 33.9 47.9 40.9
  57.8 28.1 45.1 41.7 45.2 55.5 49.6 39.1 38.9 63.8 53.5 60.9 63.6 55.6
  56.  56.2 45.  46.1 56.2 53.4 52.9 34.2 45.9 58.9 44.8 57.2 39.3 45.
  55.4 63.  45.  45.6 68.7 61.3 48.7 56.2]
 [50.7 67.2 52.1 45.2 41.2 46.  37.  48.1 67.6 40.6 58.6 53.8 49.7 37.1
  64.  53.1 50.3 40.2 53.5 62.2 44.3 49.  59.5 57.  29.2 43.  48.5 48.5
  50.1 59.1 46.  38.5 39.3 63.7 52.7 47.6 53.5 42.1 45.9 50.4 42.8 69.5
  49.2 48.6 53.6 46.9 46.8 55.6 49.8 45.4]
 [59.2 54.  52.4 43.1 50.4 41.1 36.4 48.5 46.7 40.7 46.2 47.9 30.  53.7
  38.7 60.1 44.3 44.6 38.9 44.9 52.  41.9 38.2 55.2 64.  57.3 51.4 56.2
  50.6 43.9 48.7 49.1 35.8 55.6 34.3 39.6 48.9 41.9 53.7 42.1 48.1 58.7
  49.5 5

# Задание 2.10 (4 балла)

"Разверните" массив `A` в одномерный массив. Оставьте в нём только уникальные элементы в том же порядке, в котором они встречаются в массиве. Используйте [np.unique()](https://numpy.org/doc/stable/reference/generated/numpy.unique.html)

In [16]:
import numpy as np

# Генерация массива A размерности 200x50
A = np.random.randint(0, 100, size=(200, 50))

A_flat = A.flatten()
unique_elements, unique_indices = np.unique(A_flat, return_index=True)
sorted_unique_elements = unique_elements[np.argsort(unique_indices)]

# Печать результата
print(sorted_unique_elements)


[19 38 53 39 51  5 86 73 50 35 23 33  8 82 11 16  2 83 22 64  3 42 88 93
 48 70 55 71 54 85 56 15 29 96 66 84 40 98 58 61 77 20  7 67 43 14 25 46
 28 52 32 99  4 44 68 62 45 63 78 92 12 49 65 26 30 90 57 95 37 47 17 91
 13 72 18 59  0 34 79 97  1  6 10 21  9 31 74 36 24 94 27 81 76 80 75 89
 41 69 87 60]


# Задание 2.11 (3 балла)

Создайте одномерный массив размерности $200$, в котором каждый элемент - евклидово расстояние между соответствующей строкой `A` и "усредненной" строкой матрицы `A`

In [17]:
import numpy as np

# Генерация массива A размерности 200x50
A = np.random.randint(0, 100, size=(200, 50))

# Вычисление усредненной строки (среднее по столбцам)
mean_row = np.mean(A, axis=0)

# Вычисление евклидова расстояния для каждой строки A до усредненной строки
distances = np.linalg.norm(A - mean_row, axis=1)

# Печать результата
print(distances)


[205.54302281 206.08210554 198.65229479 219.43400882 179.43832987
 198.44776196 190.63521245 202.60410713 190.99666025 217.14067842
 210.77375127 166.24329829 186.54416159 209.64227681 192.58381091
 213.70241979 200.7699784  180.64261464 197.2783927  209.0539266
 215.46369584 214.54578585 190.18912752 214.67529952 195.09752491
 216.82062684 222.77788092 213.78539292 185.46361968 195.89939823
 209.17883312 204.2986398  193.41839164 207.92146167 183.44801505
 199.52013489 198.92152781 217.5342369  200.41143736 190.89558461
 217.49920511 162.36306299 208.2623207  220.05166263 212.61971739
 213.7186801  223.3311985  206.83956156 218.19379969 200.1015098
 188.92372595 187.33895544 215.41853269 200.88856171 196.09672161
 207.6536882  195.64770437 196.235558   206.40676884 216.18277967
 187.54448599 207.18430014 199.66918697 212.39374808 188.81635052
 214.285637   216.83104996 199.42037064 209.73775107 201.00702531
 189.60003751 206.23283983 210.84345905 194.04186204 189.03096102
 191.8528452

# Задание 2.12 (2 балла)

Создайте новый массив, который состоит из элементов `A`, измененных по следующим правилам:
- если элемент меньше $50$, то он умножается на $2$
- в противном случае он умножается на $3$

Используйте [np.where()](https://numpy.org/doc/stable/reference/generated/numpy.where.html)

In [18]:
import numpy as np

A = np.random.randint(0, 100, size=(200, 50))
A_modified = np.where(A < 50, A * 2, A * 3)

# Печать результата
print(A_modified)


[[ 90 246 243 ... 297 279  38]
 [ 94  14 225 ... 261  52   2]
 [ 88 231   0 ...  82  42  82]
 ...
 [225 168  80 ... 270 204 204]
 [ 64  76  14 ...   4  90 276]
 [ 50 246   0 ... 198 168 252]]


# Задание 2.13 (4 балла)

Разверните массив `A` в одномерный массив. Создайте три новых массива, подсчитав скользящие средние по окнам $3$, $5$, $10$. Найдите сумму этих массивов, выровнив их размерности нулями справа

*Tip: реализуйте функцию, которая считает скользящее среднее. Используйте [np.cumsum()](https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html) или [np.convolve()](https://numpy.org/doc/stable/reference/generated/numpy.convolve.html)*

In [20]:
import numpy as np

# Генерация массива A размерности 200x50
A = np.random.randint(0, 100, size=(200, 50))

# Развернуть массив A в одномерный
A_flat = A.ravel()

# Функция для подсчета скользящего среднего с помощью np.convolve
def moving_average(arr, window_size):
    return np.convolve(arr, np.ones(window_size), mode='valid') / window_size

# Рассчитываем скользящие средние для окон 3, 5, 10
ma_3 = moving_average(A_flat, 3)
ma_5 = moving_average(A_flat, 5)
ma_10 = moving_average(A_flat, 10)

# Выровнять размерности с добавлением нулей справа
max_length = max(len(ma_3), len(ma_5), len(ma_10))

# Добавляем нули справа для выравнивания
ma_3 = np.pad(ma_3, (0, max_length - len(ma_3)), 'constant')
ma_5 = np.pad(ma_5, (0, max_length - len(ma_5)), 'constant')
ma_10 = np.pad(ma_10, (0, max_length - len(ma_10)), 'constant')

# Находим сумму этих массивов
sum_ma = ma_3 + ma_5 + ma_10

# Печать результатов
print("Скользящее среднее для окна 3:", ma_3)
print("Скользящее среднее для окна 5:", ma_5)
print("Скользящее среднее для окна 10:", ma_10)
print("Сумма скользящих средних:", sum_ma)


Скользящее среднее для окна 3: [64.33333333 59.66666667 47.33333333 ... 30.33333333 25.
 31.        ]
Скользящее среднее для окна 5: [59.6 60.2 50.6 ... 36.   0.   0. ]
Скользящее среднее для окна 10: [52.3 46.3 39.  ...  0.   0.   0. ]
Сумма скользящих средних: [176.23333333 166.16666667 136.93333333 ...  66.33333333  25.
  31.        ]


# Задание 2.14 (5 баллов)

Постройте график функции $$f(x) = (5  \sin(2x) - \cos^2(x) - 1 + |x^3| - x^2) / (x^2 + 1)$$  

и производной от этой функции.  Найдите минимум (например, c помощью `scipy`) и обозначьте его на графике. На этой же оси постройте графики скользящего среднего этой функции с окном $1$, $2$, $5$.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import minimize
from scipy.ndimage import uniform_filter1d

# Определяем функцию f(x)
def f(x):
    return (5 * np.sin(2 * x) - np.cos(x)**2 - 1 + np.abs(x**3) - x**2) / (x**2 + 1)

# Вычисление производной функции
def df(x):
    epsilon = 1e-5  # Маленький шаг для численного дифференцирования
    return (f(x + epsilon) - f(x - epsilon)) / (2 * epsilon)

# Генерация значений x и y для функции и производной
x = np.linspace(-10, 10, 400)
y = f(x)
dy = df(x)

# Находим минимум функции с помощью scipy.optimize.minimize
res = minimize(lambda x: f(x), 0)  # Минимизация функции начиная с точки 0
minimum_x = res.x[0]
minimum_y = f(minimum_x)

# Строим графики
plt.figure(figsize=(10, 6))

# График функции f(x)
plt.plot(x, y, label=r'$f(x)$', color='blue')

# График производной df(x)
plt.plot(x, dy, label=r"$f'(x)$", color='red')

# График скользящего среднего с окнами 1, 2, 5
sm_1 = uniform_filter1d(y, size=1)
sm_2 = uniform_filter1d(y, size=2)
sm_5 = uniform_filter1d(y, size=5)

plt.plot(x, sm_1, label=r'Skipping average (window=1)', linestyle='--', color='green')
plt.plot(x, sm_2, label=r'Skipping average (window=2)', linestyle='--', color='orange')
plt.plot(x, sm_5, label=r'Skipping average (window=5)', linestyle='--', color='purple')

# Отметим минимум на графике
plt.scatter(minimum_x, minimum_y, color='black', label=f'Minimum at x={minimum_x:.2f}, f(x)={minimum_y:.2f}')

# Настройка графика
plt.title(r'Graph of $f(x)$ and its derivative, with sliding averages')
plt.xlabel('x')
plt.ylabel('y')
plt.legend()
plt.grid(True)

# Показываем график
plt.show()


ModuleNotFoundError: No module named 'matplotlib'

# Задание 2.15 (6 баллов)

Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [ ]:
from typing import List 

def sample(x: List[int], c: int) -> List[int]:
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)   

Реализуйте данный алгоритм более оптимальным способом на массивах `numpy`, без использования циклов. Проверьте корректность и идентичность алгоритмов семплирования с помощью статистических тестов.

In [2]:
import numpy as np
from typing import List

def sample(x: List[int], c: int) -> List[int]:
    assert len(x) > 0
    
    x = np.array(x)  # Конвертируем список в numpy массив
    s = np.sum(x)  # Сумма всех элементов
    cum_sum = np.cumsum(x)  # Кумулятивная сумма
    
    # Генерируем c случайных чисел, пропорциональных сумме элементов x
    vals = np.random.random(c) * s
    
    # Находим индексы с помощью np.searchsorted, которые позволяют искать в кумулятивной сумме
    res = np.searchsorted(cum_sum, vals)
    
    return res.tolist()

# Пример использования
result = sample([50, 3, 1, 7, 20], 5)
print(result)


[4, 0, 0, 4, 0]


# Задание 2.16 (3 балла)

Есть следующий алгоритм "случайного блуждания"

In [3]:
import random 

def walk(n: int):
    cur_position = 0
    for i in range(n):
        cur_position += random.choice([-3, -1, 0, 2, 3])

    return cur_position

walk(10_000)

1782

Реализуйте более эффективную версию с помощью `numpy`, сравните производительность (используя, например, magic `timeit`). Воспользовавшись [kdeplot()](https://seaborn.pydata.org/generated/seaborn.kdeplot.html) или аналогами, постройте график распределения значений `walk(10_000)` на каком-то разумном числе запусков. 

# Задание 2.17 (3 балла)

Имеется функция, которая проделывает достаточно странные манипуляции с массивом `numpy`

In [ ]:
import numpy.typing as npt

def strange_conv(a: npt.NDArray[np.float64]) -> np.float64:
    x_len = a.shape[0]
    y_len = a.shape[1]

    t = 1.
    for y in range(y_len - 5):
        for x in range(x_len - 3):
            c = 1.5 * a[y+1, x+2] - a[y+5, x+3] * a[y, x] + 0.2 * a[y+4, x]
            t = 0.2 * t + 0.8 * c

    return t


a = np.random.random((10000, 10000))
strange_conv(a)


Оптимизируйте данную функцию с помощью (2 на выбор):
- [Numba](https://numba.pydata.org)
- `Cython` (+1 балл)
- [Taichi](https://github.com/taichi-dev/taichi) (+1 балл)
- `Pythran `[[1]](https://pythran.readthedocs.io/en/latest/), [[2]](https://serge-sans-paille.github.io/pythran-stories/pythran-tutorial.html) (+1 балл)

Сравните производительность.

In [6]:
import numpy as np
import numpy.typing as npt

def strange_conv_optimized(a: npt.NDArray[np.float64]) -> np.float64:
    x_len, y_len = a.shape
    
    a1 = a[0:y_len-5, 0:x_len-3]
    a2 = a[0:y_len-5, 0:x_len-3]  # Changed from (1:x_len-2)
    a3 = a[0:y_len-5, 0:x_len-3]
    a4 = a[4:y_len-1, 0:x_len-3]


    c = 1.5 * a1 - a2 * a3 + 0.2 * a4
    t = np.mean(c)

    return t

# Пример
a = np.random.random((10000, 10000))
result = strange_conv_optimized(a)
print(result)


0.5166255561130206
